version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - cd sam-project
      - sam build
      - sam deploy --region us-west-1 --stack-name serverlessApp  --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
