version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - cd sam-project
      - sam build
      - sam deploy --region us-west-1 --stack-name serverlessApp  --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
  post_build:
    commands:
      - cd ..
      #aws s3 sync website/ s3://myserverlesblog.ajayproject.com
      - |

        if [[ -n "$CODEBUILD_RESOLVED_SOURCE_VERSION" && -n "$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION...HEAD | grep 'website/')" ]]; then
          echo "Changes detected in 'website/' folder.";
          # Perform additional actions or commands here, e.g., sync to S3.
          aws s3 sync website/ s3://myserverlesblog.ajayproject.com
        else
          echo "No changes in 'website/' folder.";
        fi
