version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build -t sam-project/template.yaml
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --region us-west-1
