version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - cd sam-project
      - sam build
      - sam deploy --region us-west-1 --stack-name serverlessApp  --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
  post_build:
    commands:
      - cd ..
      - aws s3 sync --exclude ".*" --dryrun website/ s3://myserverlesblog.ajayproject.com/
      - if [ $? -eq 0 ]; then
        echo "No changes in the website/ folder. Skipping sync.";
        else
        echo "Syncing S3 bucket with website/ folder...";
        aws s3 sync website/ s3://myserverlesblog.ajayproject.com/;
        fi

      #aws s3 sync website/ s3://myserverlesblog.ajayproject.com
